df <- read.csv(file = "TextFile.csv")
plot(df$c, df$b)
hist(df$b, breaks = 4)
plot(df$e, df$f, xlab = "number", ylab = "square", main = "My Plot", type = "o", col = "orange")
par(col = "blue")
par(col.main = "red")
par(cex.axis = 1.5)
par(lty = 5)
plot(df$e, df$f, xlab = "number", ylab = "square", main = "My Plot", type = "o")
par()
par(mfrow = c(2, 2))
plot(df$e, df$f, xlab = "number", ylab = "square", main = "My Plot", type = "o")
plot(df$e, df$f, xlab = "number", ylab = "square", main = "My Plot", type = "o")
plot(df$e, df$f, xlab = "number", ylab = "square", main = "My Plot", type = "o")
plot(df$e, df$f, xlab = "number", ylab = "square", main = "My Plot", type = "o")

grid <- matrix(c(1, 1, 2, 3), nrow = 2, ncol = 2, byrow = TRUE)
layout(grid)
plot(df$e, df$f, xlab = "number", ylab = "square", main = "My Plot", type = "o", col = "orange")
plot(df$e, df$f, xlab = "number", ylab = "square", main = "My Plot", type = "o", col = "green")
plot(df$e, df$f, xlab = "number", ylab = "square", main = "My Plot", type = "o", col = "purple")

layout(1)
plot(df$e, df$f, xlab = "number", ylab = "square", main = "My Plot", type = "o", col = "purple")
abline(lm(df$e ~ df$f), lwd = 2)
abline(coef(lm(df$e ~ df$f)), lwd = 2)

